### ISSUE TITLE
请教一下第二种方案，运行Flask服务实现gRPC服务多进程

### ISSUE THREAD

**Issue by yjiangling** [fangjh13/gRPC-web-infer#3]
博主，关于第二种运行Flask服务实现多进程的方案能否详细讲解一下？是要先单独启动gRPC的server，然后Flask web server那边调用这个gRPC的server吗？不然单独只使用web_app.py这个脚本好像没有把服务启动起来啊？期待您的解答，非常感谢~

**Comment by fangjh13** [comment]
对的，先要启动 grpc 的服务端 (`inference_server.py`)，之后再启动 web api

**Comment by yjiangling** [comment]
> 对的，先要启动 grpc 的服务端 (`inference_server.py`)，之后再启动 web api

好的，明白了，感谢博主
